In [61]:
member = ['한세진', '김경환', '김경태', '이민하',
'조혜리', '김환선', '전민규', '안효준',
'김민석', '박란영', '김도연', '권도운',
'박지훈', '도영훈', '손지원', '김이현',
'김태헌', '김재성', '곽경민', '구성윤',
'이동건', '김현주', '황지원', '김미소',
'장재웅', '이송은', '황은혁', '박형준',
'안윤호', '이현종', '김아란', '김영주']

pandas1 = {'1조': ['한세진', '김경환', '김경태', '이민하'],
'2조': ['조혜리', '김환선', '전민규', '안효준'],
'3조': ['김민석', '박란영', '김도연', '권도운'],
'4조': ['박지훈', '도영훈', '손지원', '김이현'],
'5조': ['김태헌', '김재성', '곽경민', '구성윤'],
'6조': ['이동건', '김현주', '황지원', '김미소'],
'7조': ['장재웅', '이송은', '황은혁', '박형준'],
'8조': ['안윤호', '이현종', '김아란', '김영주']}    


visual2 = {'1조': ['이송은', '황은혁', '장재웅', '김경태'],
  '2조': ['박형준', '김경환', '박지훈', '권도운'],
  '3조': ['김아란', '한세진', '김현주', '김태헌'],
  '4조': ['이현종', '이민하', '김도연', '조혜리'],
  '5조': ['김미소', '김재성', '안효준', '황지원'],
  '6조': ['이동건', '구성윤', '곽경민', '김영주'],
  '7조': ['전민규', '김이현', '도영훈', '손지원'],
  '8조': ['안윤호', '김민석', '김환선', '박란영']}

Public3 = {'1조': ['박란영', '한세진', '곽경민', '김이현'],
'2조': ['김현주', '박형준', '김도연', '전민규'],
'3조': ['손지원', '김경환', '황지원', '김환선'],
'4조': ['안윤호', '구성윤', '안효준', '도영훈'],
'5조': ['김경태', '김영주', '김미소', '김민석'],
'6조': ['이송은', '김아란', '이민하', '권도운'],
'7조': ['조혜리', '이동건', '박지훈', '김태헌'],
'8조': ['황은혁', '김재성', '장재웅', '이현종']}


SQL4 ={'1조': ['김이현', '김환선', '이민하', '김경환', '김태헌'],
 '2조': ['김경태', '김아란', '김현주', '김영주'],
 '3조': ['황지원', '조혜리', '안효준', '박란영'],
 '4조': ['이동건', '도영훈', '김도연', '안윤호'],
 '5조': ['전민규', '김민석', '이송은', '곽경민'],
 '6조': ['한세진', '박지훈', '권도운', '장재웅'],
 '7조': ['박형준', '이현종', '손지원', '김재성']}


crawling5 = {'1조':['김이현', '김현주', '이민하', '황은혁'],
'2조':['안효준', '박지훈', '황지원', '김경태'],
'3조':['구성윤', '이동건', '김민석', '김도연'],
'4조':['김아란', '박란영', '곽경민'],
'5조':['김재성', '김태헌', '조혜리', '권도운'],
'6조': ['김영주','장재웅','이현종','안윤호'],
'7조': ['손지원', '박형준', '전민규', '한세진'],
'8조': ['김경환', '이송은', '김환선', '도영훈']}


Numpy6 = {'1조': ['김이현', '안효준', '구성윤', '곽경민'], 
'2조': ['김재성', '안윤호', '손지원', '김경환'], 
'3조': ['김아란', '이동건', '박지훈', '황은혁'], 
'4조': ['박형준', '이송은', '장재웅', '김태헌'], 
'5조': ['김현주', '황지원', '김민석', '박란영'], 
'6조': ['조혜리', '전민규', '김영주', '김환선'], 
'7조': ['이민하', '김경태', '김도연', '한세진'],
'8조': ['이현종', '권도운', '도영훈']}


ML7 = {
'1조': ['김재성', '도영훈', '박지훈', '박형준'],
  '2조': ['김경태', '김태헌', '이동건', '김이현'],
  '3조': ['이현종', '김현주', '안효준', '전민규'],
  '4조': ['황지원', '김아란', '김환선', '권도운'],
  '5조': ['손지원', '이송은', '김민석', '이민하'],
  '6조': ['김경환', '김미소', '김도연', '김영주'],
  '7조': ['박란영', '장재웅', '한세진', '구성윤'],
  '8조': ['조혜리', '곽경민', '안윤호', '황은혁']}

In [62]:
# members = ['한세진', '김경환', '김경태', '이민하', '조혜리', '김환선', '전민규', '안효준', 
#            '김민석', '박란영', '김도연', '권도운', '박지훈', '도영훈', '손지원', '김이현', 
#            '김태헌', '김재성', '곽경민', '구성윤', '이동건', '김현주', '황지원', '김미소', 
#            '장재웅', '이송은', '황은혁', '박형준', '안윤호', '이현종', '김아란', '김영주']

# members.sort()
# idx = 0
# for i in members:
#     print(f'\'{i}\',',end=" ")
#     idx+=1
#     if idx % 5 == 0:
#         print()

In [63]:
members = ['곽경민', '구성윤', '권도운', '김경태', '김경환', 
'김도연', '김미소', '김민석', '김아란', '김영주', 
'김이현', '김재성', '김태헌', '김현주', '김환선', 
'도영훈', '박란영', '박지훈', '박형준', '손지원', 
'안윤호', '안효준', '이동건', '이민하', '이송은', 
'이현종', '장재웅', '전민규', '조혜리', '한세진', 
'황은혁', '황지원']

In [64]:
import pandas as pd
import numpy as np

members = ['곽경민', '구성윤', '권도운', '김경태', '김경환', 
'김도연', '김미소', '김민석', '김아란', '김영주', 
'김이현', '김재성', '김태헌', '김현주', '김환선', 
'도영훈', '박란영', '박지훈', '박형준', '손지원', 
'안윤호', '안효준', '이동건', '이민하', '이송은', 
'이현종', '장재웅', '전민규', '조혜리', '한세진', 
'황은혁', '황지원']

# 조 구성 딕셔너리들
groups = [pandas1, visual2, Public3, SQL4, crawling5, Numpy6, ML7]

# 빈 데이터프레임 생성
df = pd.DataFrame(0, index=members, columns=members)

# 같은 조에 속한 횟수 계산
for group in groups:
    for team in group.values():
        for i in range(len(team)):
            for j in range(i + 1, len(team)):
                df.loc[team[i], team[j]] += 1
                df.loc[team[j], team[i]] += 1

# 결과 출력
df

,곽경민,구성윤,권도운,김경태,김경환,김도연,김미소,김민석,김아란,김영주,...,이동건,이민하,이송은,이현종,장재웅,전민규,조혜리,한세진,황은혁,황지원
곽경민,0,3,0,0,0,0,0,1,1,1,...,1,0,1,0,0,1,1,1,1,0
구성윤,3,0,0,0,0,1,0,1,0,1,...,2,0,0,0,1,0,0,1,0,0
권도운,0,0,0,0,1,1,0,1,2,0,...,0,1,1,1,1,0,1,1,0,1
김경태,0,0,0,0,1,1,1,1,1,2,...,1,2,1,0,1,0,0,2,1,1
김경환,0,0,1,1,0,1,1,0,0,1,...,0,2,1,0,0,0,0,1,0,1
김도연,0,1,1,1,1,0,1,2,0,1,...,2,2,0,1,0,1,1,1,0,0
김미소,0,0,0,1,1,1,0,1,0,2,...,1,0,0,0,0,0,0,0,0,2
김민석,1,1,1,1,0,2,1,0,0,1,...,1,1,2,0,0,1,0,0,0,1
김아란,1,0,2,1,0,0,0,0,0,2,...,1,1,1,1,0,0,0,1,1,1
김영주,1,1,0,2,1,1,2,1,2,0,...,1,0,0,2,1,1,1,0,0,0
김이현,2,1,0,1,1,0,0,0,0,0,...,1,2,0,0,0,1,0,1,1,0
김재성,1,1,1,0,1,0,1,0,0,0,...,0,0,0,2,1,0,1,0,1,1
김태헌,1,1,1,1,1,0,0,0,1,0,...,2,1,1,0,1,0,2,1,0,0
김현주,0,0,0,1,0,1,1,1,2,1,...,1,1,0,1,0,2,0,1,1,2
김환선,0,0,1,0,3,0,0,1,1,1,...,0,1,1,0,0,2,2,0,0,2
도영훈,0,1,1,0,1,1,0,0,0,0,...,1,0,1,1,0,1,0,0,0,0
박란영,2,1,1,0,0,1,0,3,1,0,...,0,0,0,0,1,0,1,2,0,2
박지훈,0,0,2,1,1,0,0,0,1,0,...,2,0,0,0,1,0,1,1,1,1
박형준,0,0,1,0,1,1,0,0,0,0,...,0,0,2,1,2,2,0,1,1,0
손지원,0,0,0,0,2,0,0,1,0,0,...,0,1,1,1,0,2,0,1,0,1
안윤호,1,1,0,0,1,1,0,1,1,2,...,1,0,0,2,1,0,1,0,1,0
안효준,1,2,0,1,0,0,1,0,0,0,...,0,0,0,1,0,2,2,0,0,3
이동건,1,2,0,1,0,2,1,1,1,1,...,0,0,0,0,0,0,1,0,1,1
이민하,0,0,1,2,2,2,0,1,1,0,...,0,0,2,1,0,0,1,2,1,0
이송은,1,0,1,1,1,0,0,2,1,0,...,0,2,0,0,3,1,0,0,2,0
이현종,0,0,1,0,0,1,0,0,1,2,...,0,1,0,0,2,1,1,0,1,0
장재웅,0,1,1,1,0,0,0,0,0,1,...,0,0,3,2,0,0,0,2,3,0
전민규,1,0,0,0,0,1,0,1,0,1,...,0,0,1,1,0,0,2,1,0,0
조혜리,1,0,1,0,0,1,0,0,0,1,...,1,1,0,1,0,2,0,0,1,1
한세진,1,1,1,2,1,1,0,0,1,0,...,0,2,0,0,2,1,0,0,0,0
황은혁,1,0,0,1,0,0,0,0,1,0,...,1,1,2,1,3,0,1,0,0,0
황지원,0,0,1,1,1,0,2,1,1,0,...,1,0,0,0,0,0,1,0,0,0

In [65]:
# import itertools
# import random

# # 4명씩 가능한 조합을 찾기
# possible_combinations = list(itertools.combinations(members, 4))

# # 중복 횟수 계산 함수
# def calculate_group_overlap(group, df):
#     overlap = 0
#     for i in range(len(group)):
#         for j in range(i + 1, len(group)):
#             overlap += df.loc[group[i], group[j]]
#     return overlap

# # 중복 횟수가 4 이하인 조합 찾기
# valid_groups = []

# for group in possible_combinations:
#     overlap = calculate_group_overlap(group, df)
#     if overlap <= 4:
#         valid_groups.append(group)

# # 8개의 조를 랜덤으로 선택
# random.shuffle(valid_groups)  # 조합을 섞음
# final_groups = []

# while len(final_groups) < 8:
#     group = valid_groups.pop()
#     if all(member not in itertools.chain(*final_groups) for member in group):  # 중복 멤버 없을 때만 추가
#         final_groups.append(group)

# # 결과 출력
# for i, group in enumerate(final_groups):
#     print(f"{i+1}조: {group}, 중복 점수 {overlap}")

In [84]:
import itertools
import random

# 4명씩 가능한 조합을 찾기
possible_combinations = list(itertools.combinations(members, 4))

# 중복 횟수 및 함께 해본 사람들 추적 함수
def calculate_group_overlap(group, df):
    overlap = 0
    overlap_members = []
    for i in range(len(group)):
        for j in range(i + 1, len(group)):
            current_overlap = df.loc[group[i], group[j]]
            overlap += current_overlap
            if current_overlap > 0:
                overlap_members.append((group[i], group[j], current_overlap))
    return overlap, overlap_members

# 중복 횟수가 4 이하인 조합 찾기
valid_groups = []

for group in possible_combinations:
    overlap, overlap_members = calculate_group_overlap(group, df)
    if overlap <= 4:
        valid_groups.append((group, overlap, overlap_members))

# 8개의 조를 랜덤으로 선택
random.shuffle(valid_groups)  # 조합을 섞음
final_groups = []

while len(final_groups) < 8:
    group_data = valid_groups.pop()
    group = group_data[0]
    if all(member not in itertools.chain(*[g[0] for g in final_groups]) for member in group):  # 중복 멤버 없을 때만 추가
        final_groups.append(group_data)

# 결과 출력
for i, (group, overlap, overlap_members) in enumerate(final_groups):
    # print(f"{i+1}조: {group} (중복 횟수: {overlap})")
    print(f"{i+1}조: {group}", end="\t\t")
    if overlap_members:
        print("중복 이력 : ", end=" ")
        for pair in overlap_members:
            print(f"    {pair[0]} - {pair[1]}: {pair[2]}번", end=" ")
        print()
    else:
        print("  함께 해본 경험 없음")

1조: ('김미소', '이현종', '전민규', '황은혁')		중복 이력 :      이현종 - 전민규: 1번     이현종 - 황은혁: 1번
2조: ('권도운', '김민석', '김현주', '박형준')		중복 이력 :      권도운 - 김민석: 1번     권도운 - 박형준: 1번     김민석 - 김현주: 1번     김현주 - 박형준: 1번
3조: ('김아란', '김태헌', '김환선', '손지원')		중복 이력 :      김아란 - 김태헌: 1번     김아란 - 김환선: 1번     김태헌 - 김환선: 1번     김환선 - 손지원: 1번
4조: ('구성윤', '김도연', '이민하', '황지원')		중복 이력 :      구성윤 - 김도연: 1번     김도연 - 이민하: 2번
5조: ('박란영', '박지훈', '이송은', '조혜리')		중복 이력 :      박란영 - 조혜리: 1번     박지훈 - 조혜리: 1번
6조: ('곽경민', '안윤호', '이동건', '장재웅')		중복 이력 :      곽경민 - 안윤호: 1번     곽경민 - 이동건: 1번     안윤호 - 이동건: 1번     안윤호 - 장재웅: 1번
7조: ('김영주', '김이현', '안효준', '한세진')		중복 이력 :      김이현 - 안효준: 1번     김이현 - 한세진: 1번
8조: ('김경태', '김경환', '김재성', '도영훈')		중복 이력 :      김경태 - 김경환: 1번     김경환 - 김재성: 1번     김경환 - 도영훈: 1번     김재성 - 도영훈: 1번

In [80]:
import itertools
import random

# 4명씩 가능한 조합을 찾기
possible_combinations = list(itertools.combinations(members, 4))

# 중복 횟수 및 함께 해본 사람들 추적 함수
def calculate_group_overlap(group, df):
    overlap = 0
    overlap_members = []
    for i in range(len(group)):
        for j in range(i + 1, len(group)):
            current_overlap = df.loc[group[i], group[j]]
            overlap += current_overlap
            if current_overlap > 0:
                overlap_members.append((group[i], group[j], current_overlap))
    return overlap, overlap_members

# 중복 횟수가 4 이하인 조합 찾기
valid_groups = []

for group in possible_combinations:
    overlap, overlap_members = calculate_group_overlap(group, df)
    if overlap <= 4:  # 중복 점수를 4로 제한
        valid_groups.append((group, overlap, overlap_members))

# 8개의 조를 랜덤으로 선택
random.shuffle(valid_groups)  # 조합을 섞음
final_groups = []

# 중복 경험이 2회인 사람들을 추적
pairs_to_avoid = set()

# 중복 횟수 2 이상인 조합을 추적
for group in valid_groups:
    overlap_members = group[2]
    for pair in overlap_members:
        if pair[2] == 2:  # 중복 횟수가 2인 경우
            pairs_to_avoid.add((pair[0], pair[1]))

# 조를 구성
while len(final_groups) < 8 and valid_groups:
    group_data = valid_groups.pop()
    group = group_data[0]

    # 조원 중 중복 경험이 2회인 경우 제외
    if all((member not in itertools.chain(*pairs_to_avoid) for member in group)):
        if all(member not in itertools.chain(*[g[0] for g in final_groups]) for member in group):  # 중복 멤버 없을 때만 추가
            final_groups.append(group_data)

# 결과 출력
if len(final_groups) < 8:
    print(f"충분한 조합을 찾지 못했습니다. 가능한 조합 수: {len(final_groups)}")
else:
    for i, (group, overlap, overlap_members) in enumerate(final_groups):
        print(f"{i+1}조: {group} (중복 횟수: {overlap})")
        if overlap_members:
            print("  함께 해본 사람들:")
            for pair in overlap_members:
                print(f"    {pair[0]} - {pair[1]}: {pair[2]}번")
        else:
            print("  함께 해본 경험 없음")

충분한 조합을 찾지 못했습니다. 가능한 조합 수: 0