In [2]:
import matplotlib.pyplot as plt
import koreanize_matplotlib
import pandas as pd
import csv


file_name = 'Climate_year_DF.xlsx'
storm = 'pacific.csv'
Climate = pd.read_excel(file_name)
Cyclone = pd.read_csv(storm)

# Cyclone['Date'] = pd.to_datetime(Cyclone['Date'])
# 1980 ~ 2010 
Cyclone['Date']	=	pd.to_datetime(Cyclone['Date'],	format='%Y%m%d')
Cyclone = Cyclone[(Cyclone['Date'].dt.year>=1980) & (Cyclone['Date'].dt.year<=2010)]
Cyclone.drop(['Low Wind NE','Low Wind SE','Low Wind SW','Low Wind NW','Moderate Wind NE','Moderate Wind SE','Moderate Wind SW','Moderate Wind NW','High Wind NE','High Wind SE','High Wind SW','High Wind NW'], axis=1, inplace=True)
Cyclone['Name']= Cyclone['Name'].str.rstrip().str.lstrip()



Created_Cyclone = []
for y in range(1980,2011):
    Created_Cyclone.append(len(Cyclone[Cyclone['Date'].dt.year == y]['ID'].unique()))
# Created_Cyclone

In [3]:
StatusDF = pd.DataFrame(columns=['year','Hurricane'])
S_Cy = Cyclone[Cyclone['Status']==' TS']
S_Cy['ID']
# len(S_Cy['ID'].unique())          # 276

7628     EP011980
7629     EP011980
7630     EP011980
7631     EP011980
7644     EP011980
           ...
23090    CP012010
23091    CP012010
23092    CP012010
23093    CP012010
23094    CP012010
Name: ID, Length: 5421, dtype: object

In [4]:
Cy_list = list(S_Cy['ID'].unique())
# Cy_list

In [6]:
plz = []
year_list = [i for i in range(1980,2011)]
for i in year_list:
    plz.append(len(S_Cy[S_Cy['Date'].dt.year==i]['ID'].unique()))
for i in plz:
    print(i,end=',')

14,15,23,21,21,23,17,20,15,17,21,14,27,15,20,10,9,19,13,9,19,16,15,16,12,15,19,11,17,20,8,

In [38]:
len(S_Cy[S_Cy['Date'].dt.year==1980]['ID'].unique())

7

In [35]:
year_list = [i for i in range(1980,2011)]
Cyc_list = []   # 넣은 아이디 append
idx = 0
for i in year_list:
    # StatusDF.loc[idx] = [S_Cye[S_Cy['Date'].dt.year==i]['Date'].dt.year]
    for c in Cy_list:   # 태풍 아이디 리스트
        Cyc_list.append(S_Cy[(S_Cy['Date'].dt.year==i) & (S_Cy['ID']==c)]['ID'])
        if S_Cy[S_Cy['Date'].dt.year==i]['ID'] in Cyc_list: # 확인용 리스트
            break
    idx += 1
    # if S_Cy[S_Cy['Date'].dt.year==i]['ID']

ValueError: Can only compare identically-labeled Series objects

In [34]:
Cyc_list

[7632    EP011980
 7633    EP011980
 7634    EP011980
 7635    EP011980
 7636    EP011980
 7637    EP011980
 7638    EP011980
 7639    EP011980
 7640    EP011980
 7641    EP011980
 7642    EP011980
 7643    EP011980
 Name: ID, dtype: object,
 7672    EP031980
 7673    EP031980
 7674    EP031980
 7675    EP031980
 7676    EP031980
 7677    EP031980
 7678    EP031980
 7679    EP031980
 Name: ID, dtype: object,
 7726    EP071980
 Name: ID, dtype: object,
 7743    EP081980
 7744    EP081980
 7745    EP081980
 7746    EP081980
 7747    EP081980
 7748    EP081980
 7749    EP081980
 7750    EP081980
 7751    EP081980
 7752    EP081980
 7753    EP081980
 7754    EP081980
 7755    EP081980
 7756    EP081980
 7757    EP081980
 7758    EP081980
 Name: ID, dtype: object,
 7772    EP091980
 7773    EP091980
 7774    EP091980
 7775    EP091980
 7776    EP091980
 7777    EP091980
 7778    EP091980
 7779    EP091980
 7780    EP091980
 7781    EP091980
 Name: ID, dtype: object,
 7794    EP101980
 7795    EP101980
 7796    EP101980
 7797    EP101980
 7798    EP101980
 7799    EP101980
 7800    EP101980
 7801    EP101980
 7802    EP101980
 7803    EP101980
 7804    EP101980
 7805    EP101980
 7806    EP101980
 Name: ID, dtype: object,
 7819    EP111980
 7820    EP111980
 7821    EP111980
 7822    EP111980
 7823    EP111980
 7824    EP111980
 7825    EP111980
 7826    EP111980
 7827    EP111980
 7828    EP111980
 7829    EP111980
 7830    EP111980
 7831    EP111980
 7842    EP111980
 7843    EP111980
 7844    EP111980
 7845    EP111980
 7846    EP111980
 7847    EP111980
 7848    EP111980
 7849    EP111980
 7850    EP111980
 7851    EP111980
 7852    EP111980
 7853    EP111980
 7854    EP111980
 7855    EP111980
 7856    EP111980
 7857    EP111980
 7858    EP111980
 7859    EP111980
 Name: ID, dtype: object,
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 7926    EP021981
 7927    EP021981
 7928    EP021981
 7929    EP021981
 7930    EP021981
 7931    EP021981
 7932    EP021981
 7933    EP021981
 7934    EP021981
 7935    EP021981
 Name: ID, dtype: object,
 7970    EP041981
 7971    EP041981
 7972    EP041981
 7973    EP041981
 7974    EP041981
 7975    EP041981
 7976    EP041981
 7977    EP041981
 7978    EP041981
 7979    EP041981
 7980    EP041981
 Name: ID, dtype: object,
 8018    EP061981
 8019    EP061981
 8020    EP061981
 8021    EP061981
 8022    EP061981
 8023    EP061981
 8024    EP061981
 8025    EP061981
 8026    EP061981
 8027    EP061981
 Name: ID, dtype: object,
 8062    EP071981
 8063    EP071981
 Name: ID, dtype: object,
 8088    EP081981
 8089    EP081981
 8090    EP081981
 8091    EP081981
 8092    EP081981
 Name: ID, dtype: object,
 8122    EP101981
 8123    EP101981
 8124    EP101981
 8125    EP101981
 8126    EP101981
 8127    EP101981
 8128    EP101981
 8129    EP101981
 8130    EP101981
 8131    EP101981
 8132    EP101981
 Name: ID, dtype: object,
 8180    EP141981
 8181    EP141981
 8182    EP141981
 8183    EP141981
 8184    EP141981
 8185    EP141981
 8186    EP141981
 8187    EP141981
 8188    EP141981
 8189    EP141981
 8190    EP141981
 8191    EP141981
 Name: ID, dtype: object,
 8202    EP151981
 8203    EP151981
 8204    EP151981
 8205    EP151981
 8206    EP151981
 8207    EP151981
 8208    EP151981
 8209    EP151981
 8210    EP151981
 8211    EP151981
 8212    EP151981
 8213    EP151981
 Name: ID, dtype: object,
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),
 Series([], Name: ID, dtype: object),

In [18]:
StatusDF

           0
0        NaN
1  Hurricane

In [3]:
Cyclone['Latitude_Alpha'] =  Cyclone['Latitude'].str[-1]
Cyclone['Longitude_Alpha'] =  Cyclone['Longitude'].str[-1]

In [4]:
Cyclone['Latitude'] = Cyclone['Latitude'].str.replace('N','')
Cyclone['Latitude'] = Cyclone['Latitude'].str.replace('S','')
Cyclone['Longitude'] = Cyclone['Longitude'].str.replace('W','')
Cyclone['Longitude'] = Cyclone['Longitude'].str.replace('E','')

In [5]:
Cyclone['Status']==HU

NameError: name 'HU' is not defined

In [ ]:
Cyclone['Latitude'] = Cyclone['Latitude'].astype('float')
Cyclone['Longitude'] = Cyclone['Longitude'].astype('float')

In [ ]:
Cyclone['Latitude'].info()

<class 'pandas.core.series.Series'>
Index: 15476 entries, 7625 to 23100
Series name: Latitude
Non-Null Count  Dtype
--------------  -----
15476 non-null  float64
dtypes: float64(1)
memory usage: 241.8 KB

## 필리핀 분석

In [ ]:
Pili_cy = Cyclone[(Cyclone['Latitude']<=21.2) & (Cyclone['Latitude']>=4.3) & (Cyclone['Latitude_Alpha']=='N')]
Pili_cy = Pili_cy[(Pili_cy['Longitude']<=127.3) & (Pili_cy['Longitude']>=114.1)& (Cyclone['Latitude_Alpha']=='E')]

C:\Users\kjy19\AppData\Local\Temp\ipykernel_20172\1693196491.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  Pili_cy = Pili_cy[(Pili_cy['Longitude']<=127.3) & (Pili_cy['Longitude']>=114.1)& (Cyclone['Latitude_Alpha']=='E')]

In [ ]:
Pili_cy

Empty DataFrame
Columns: [ID, Name, Date, Time, Event, Status, Latitude, Longitude, Maximum Wind, Minimum Pressure, Latitude_Alpha, Longitude_Alpha]
Index: []

In [ ]:
Korea_cy = Cyclone[(Cyclone['Latitude']<=43) & (Cyclone['Latitude']>=33) & (Cyclone['Latitude_Alpha']=='N')]
Korea_cy = Korea_cy[(Korea_cy['Longitude']<=132) & (Korea_cy['Longitude']>=124) & (Korea_cy['Latitude_Alpha']=='E')]

In [ ]:
Korea_cy

Empty DataFrame
Columns: [ID, Name, Date, Time, Event, Status, Latitude, Longitude, Maximum Wind, Minimum Pressure, Latitude_Alpha, Longitude_Alpha]
Index: []

In [ ]:
Usa_cy = Cyclone[(Cyclone['Latitude']<=48) & (Cyclone['Latitude']>=24) & (Cyclone['Latitude_Alpha']=='N')]
Usa_cy = Korea_cy[(Korea_cy['Longitude']<=125) & (Korea_cy['Longitude']>=48) & (Korea_cy['Latitude_Alpha']=='W')]

In [ ]:
Usa_cy

Empty DataFrame
Columns: [ID, Name, Date, Time, Event, Status, Latitude, Longitude, Maximum Wind, Minimum Pressure, Latitude_Alpha, Longitude_Alpha]
Index: []